[package]
name = "ledger"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

canton-api-client = "3.3.0-0.1.0"
futures-util = "0.3.31"
log = "0.4.17"
url = "2.5.4"
reqwest = { workspace = true, features = ["json"] }
tokio-tungstenite-wasm = { version = "0.8", features = ["rustls-tls-webpki-roots"] }

common = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tokio-macros = { workspace = true }

dotenvy = { workspace = true }

keycloak = { workspace = true }
